name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        device: [a50, m30s]
        variant: [oneui, aosp, recovery]
        ksu: ['', -k]
        susfs: ['', -s]
        selinux: ['', -p]
        exclude:
          - ksu: ''
            susfs: -s
            selinux: ''
          - ksu: ''
            susfs: -s
            selinux: -p

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt install make libssl-dev curl bc pkg-config m4 libtool automake autoconf libelf-dev bzip2 p7zip-full jq python3 python-is-python3 -y 

      - name: Run build 
        run: |
          export ROM=${{ matrix.rom }}
          export KSU=${{ matrix.ksu }}
          export SUSFS=${{ matrix.susfs }}
          export SELINUX=${{ matrix.selinux }}
          export DEVICE=${{ matrix.device }}
          export VARIANT=${{ matrix.variant }}
          ./build.sh -d $DEVICE -v $VARIANT $KSU $SUSFS $SELINUX --android 12

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}-${{ matrix.variant }}-${{ matrix.ksu }}-${{ matrix.susfs }}-${{ matrix.selinux }}
          path: out/

      # Tek release oluşturulsun (sadece ilk job yapacak)
      - name: Create GitHub Release
        if: github.run_number == 1
        uses: softprops/action-gh-release@v1
        with:
          tag_name: android12-${{ github.run_id }}
          name: Mint kernel
          body: |
            Automated kernel build for ALL devices and variants
            Android 11 to 16
            Your warranty is now void. I am not responsible for bricked devices, dead SD cards.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Her job kendi ZIP’ini aynı release’e ekler
      - name: Upload ZIPs to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: android12-${{ github.run_id }}
          files: out/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
